import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

class SupabaseAdminService {
  static const String _urlProjeto = 'https://baqpfticrbesvnjgrlpb.supabase.co';

  const SupabaseAdminService();

  Future<String> criarTabelas({
    required String serviceRoleKey,
  }) async {
    final endpoint = Uri.parse('$_urlProjeto/rest/v1/rpc/executar_sql_admin');
    final chaveMascarada = serviceRoleKey.length <= 12
        ? '***'
        : '${serviceRoleKey.substring(0, 6)}...${serviceRoleKey.substring(serviceRoleKey.length - 4)}';
    final sql = '''
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario TEXT UNIQUE NOT NULL,
  senha TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS vendas_ingressos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_comprador TEXT NOT NULL,
  quantidade_ingressos INTEGER NOT NULL,
  valor_total NUMERIC NOT NULL,
  parcelamento INTEGER NOT NULL,
  usuario_vendedor TEXT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  valor_recebido NUMERIC NOT NULL DEFAULT 0,
  status_pagamento TEXT NOT NULL DEFAULT 'pendente',
  recebido_em TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS recibos_pagamento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venda_id BIGINT NOT NULL REFERENCES vendas_ingressos(id) ON DELETE CASCADE,
  valor NUMERIC NOT NULL,
  recebido_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS eventos_sincronizacao_pendentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_entidade TEXT NOT NULL,
  id_entidade BIGINT,
  operacao TEXT NOT NULL,
  carga JSONB,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sincronizado_em TIMESTAMPTZ
);
''';

    debugPrint('[SYNC] Iniciando criacao de tabelas no Supabase');
    debugPrint('[SYNC] Endpoint: $endpoint');
    debugPrint('[SYNC] Chave (mascarada): $chaveMascarada');
    debugPrint('[SYNC] Tamanho SQL: ${sql.length} caracteres');

    try {
      final response = await http.post(
        endpoint,
        headers: {
          'apikey': serviceRoleKey,
          'Authorization': 'Bearer $serviceRoleKey',
          'Content-Type': 'application/json',
        },
        body: jsonEncode({'sql': sql}),
      );

      debugPrint('[SYNC] Status HTTP: ${response.statusCode}');
      debugPrint('[SYNC] Resposta: ${response.body}');

      if (response.statusCode >= 200 && response.statusCode < 300) {
        debugPrint('[SYNC] Sucesso ao criar/verificar tabelas');
        return 'Tabelas criadas/verificadas com sucesso no Supabase.';
      }

      throw Exception(
        'Falha ao criar tabelas. Status ${response.statusCode}: ${response.body}',
      );
    } catch (error, stackTrace) {
      debugPrint('[SYNC] Erro na requisicao: $error');
      debugPrint('[SYNC] Stacktrace: $stackTrace');
      rethrow;
    }
  }
}
